import { SongType } from "./SongType";

export const songs: SongType[] = [
    {
      id: 0,
      name: "Lo-fi Beat - Adventure Time",
      artist: "L.Dre",
      img: "adventuretime",
      src: "adventuretime",
    },
    {
      id: 1,
      name: "Lo-fi Beat - Arcane",
      artist: "Samuel Kim",
      img: "arcane",
      src: "arcane",
    },
    {
      id: 2,
      name: "Lo-fi Beat - Blind In Love",
      artist: "Lee",
      img: "blindinlove",
      src: "blindinlove",
    },
    {
      id: 3,
      name: "Lo-fi Beat - Blue Moon",
      artist: "Eric Godlow",
      img: "bluemoon",
      src: "bluemoon",
    },
    {
      id: 4,
      name: "Lo-fi Beat - Close To You",
      artist: "Lee",
      img: "closetoyou",
      src: "closetoyou",
    },
    {
      id: 5,
      name: "Lo-fi Beat - Dreaming of You",
      artist: "GC",
      img: "dreamingofyou",
      src: "dreamingofyou",
    },
    {
      id: 6,
      name: "Lo-fi Beat - 90's Freestyle",
      artist: "Yusei",
      img: "freestyle",
      src: "freestyle",
    },
    {
      id: 7,
      name: "Lo-fi Beat - Gravity Falls",
      artist: "L.Dre",
      img: "gravityfalls",
      src: "gravityfalls",
    },
    {
      id: 8,
      name: "Lo-fi Beat - I Need a Girl",
      artist: "Lee",
      img: "ineedagirl",
      src: "ineedagirl",
    },
    {
      id: 9,
      name: "Lo-fi Beat - Lovely",
      artist: "Eric Godlow",
      img: "lovely",
      src: "lovely",
    },
    {
      id: 10,
      name: "Lo-fi Beat - Mortified",
      artist: "L.Dre",
      img: "mortified",
      src: "mortified",
    },
    {
      id: 11,
      name: "Lo-fi Beat - Rainin Outside",
      artist: "Akitō",
      img: "rainin",
      src: "raininoutside",
    },
    {
      id: 12,
      name: "Lo-fi Beat - Rickroll But It's Lofi",
      artist: "KCFM",
      img: "rickroll",
      src: "rickroll",
    },
    {
      id: 13,
      name: "Lo-fi Beat - Sad Nights",
      artist: "Eric Godlow",
      img: "sad",
      src: "sadnights",
    },
    {
      id: 14,
      name: "Lo-fi Beat - Steven Universe",
      artist: "L.Dre",
      img: "steven",
      src: "stevenuniverse",
    },
  ];
